default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: bookApp_development
  username: postgres
  password: 22102208
  host: localhost

test:
  <<: *default
  database: bookApp_test
  username: postgres
  password: 22102208
  host: localhost

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
