default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: 22102208
  host: localhost

development:
  <<: *default
  database: bookApp_development

test:
  <<: *default
  database: bookApp_test

production:
  <<: *default
  database: bookApp_production
